name: "CMake: Build and Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Deps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libeigen3-dev 
        git clone https://github.com/google/glog.git
        cd glog
        cmake -S . -B build -G "Unix Makefiles"
        cmake --build build
        sudo cmake --install build

    - name: Configure CMake
      shell: bash
      run: |
        cd ${{github.workspace}}
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    # TODO(lschmid) messes with finding glog somehow
    # - name: Build
    #   shell: bash
    #   run: cmake --build ${{github.workspace}}/build

    # - name: Test
    #   working-directory: ${{github.workspace}}/build
    #   shell: bash
    #   run: ctest -C ${{env.BUILD_TYPE}}
